apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.projectData.namespace }}
  name: {{ .Values.projectData.deploymentName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.projectData.name }}
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.projectData.name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.projectData.name }}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: {{ .Values.resources.memoryLimit}}
          requests:
            cpu: {{ .Values.resources.cpuRequest }}
            memory: {{ .Values.resources.memoryRequest }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.projectData.namespace }}
  name: {{ .Values.projectData.serviceName }}
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Values.projectData.name }}