FROM python:3.10.2-buster as builder
COPY requirements.txt .
COPY hello.py test.py ./
RUN pip install --user --no-warn-script-location -r requirements.txt

FROM python:3.10.2-slim-buster

ENV PIP_USER="yes"
ENV PIP_NO_CACHE_DIR="yes"

# Criando user python
ENV HOME=/home/python
RUN groupadd -r -g 1000 python &&\
    useradd -lmr -g python -u 1000 python

# Definindo workspace
ENV WORKSPACE=$HOME/app
WORKDIR $WORKSPACE

# Copiando diretorios importantes do stage anterior
COPY --chown=python:python --from=builder /root/.local/ $HOME/.local/
COPY --chown=python:python --from=builder /usr/lib/ /usr/lib/
COPY --chown=python:python --from=builder test.py $WORKSPACE
COPY --chown=python:python --from=builder hello.py $WORKSPACE

ENV PATH $PATH:$HOME/.local/bin:

# Variaveis para guinicorn
ENV TIMEOUT=1000
ENV WORKERS=1
ENV THREADS=2
ENV LOG_LEVEL=debug
ENV PORT=5000

USER python

# Inicia aplicacao usando o gunicorn em vez do servidor padrao do flask
CMD ["/bin/sh", "-c", "gunicorn --timeout $TIMEOUT --workers $WORKERS --threads $THREADS --log-level $LOG_LEVEL --bind 0.0.0.0:$PORT hello:app"]